CREATE DEFINER=`root`@`localhost` PROCEDURE `Type_of_service`()
BEGIN
SELECT supplier.SUPP_ID, supplier.SUPP_NAME,rating.RAT_RATSTARS,
CASE
    WHEN RAT_RATSTARS =5  THEN 'EXCELLENT'
    WHEN RAT_RATSTARS >4  THEN 'GOOD SERVICE'
    WHEN RAT_RATSTARS >2 THEN 'AVG SERVICE'
    ELSE 'POOR SERVICE'
END AS TYPE_OF_SERVICE
FROM supplier join rating ;
END